version: '3'

services:
  db:
    build:
      context: ./db
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
    entrypoint:
      - sh
      - /backend/entrypoint.sh
    ports:
      - 5551:5000
    volumes:
      - $PWD/backend:/backend
    working_dir: /backend
    restart: on-failure

  frontend:
    build:
      context: ./frontend
    ports:
      - 5552:3000
    volumes:
      - $PWD/frontend:/app
      - /app/node_modules
    restart: on-failure
    environment:
      - CHOKIDAR_USEPOLLING=true

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5553:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@local.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
