version: '3'

services:
  reverse_proxy:
    image: nginx:1.17-alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: always

  db:
    build: ./db
    expose:
      - 5432

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    expose:
      - 5000
    restart: on-failure

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    expose:
      - 3000
    restart: on-failure
    environment:
      - CHOKIDAR_USEPOLLING=true

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=pg@pg.com
      - PGADMIN_DEFAULT_PASSWORD=pg
