version: '3'

services:
  proxy:
    build: ./reverse_proxy
    ports:
      - 80:80
    restart: always

  db:
    build: ./db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=secret
      - MONGO_INITDB_ROOT_PASSWORD=secret

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=secret
      - MONGO_INITDB_ROOT_PASSWORD=secret

#  frontend:
#    build: ./frontend
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    restart: on-failure
#    environment:
#      - CHOKIDAR_USEPOLLING=true
